#include "gtest/gtest.h"
#include "mg_math.h"


TEST(mgMathTest, mgAngleLimit)
{
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(0.0f)), DEGREES_TO_RADIANS(0.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(90.0f)), DEGREES_TO_RADIANS(90.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(-90.0f)), DEGREES_TO_RADIANS(-90.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(225.0f)), DEGREES_TO_RADIANS(-135.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(-225.0f)), DEGREES_TO_RADIANS(135.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(270.0f)), DEGREES_TO_RADIANS(-90.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(-270.0f)), DEGREES_TO_RADIANS(90.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(1100.0f)), DEGREES_TO_RADIANS(20.0f));
  EXPECT_FLOAT_EQ(mgAngleLimit(DEGREES_TO_RADIANS(-1100.0f)), DEGREES_TO_RADIANS(-20.0f));
}