name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  Windows-Latest:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Run Common Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: bin\common-test-release-x64.exe

    - name: Run Game Tests
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: bin\game-test-release-x64.exe

    - name: Create Symbols Archive
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: |
        & "C:\Program Files\7-Zip\7z.exe" a opencloud-release-symbols-x64.zip .\bin\*.pdb

    - name: Create Release Archive
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: |
        ren bin\host-release-x64.exe opencloud.exe
        & "C:\Program Files\7-Zip\7z.exe" a opencloud-release-x64.zip .\bin\opencloud.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "windows-x64-msbuild"
        path: "opencloud-release-x64.zip"