name: Ninja

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Generate Build
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake.exe -DCMAKE_BUILD_TYPE=Release -S. -B./build -G Ninja

    - name: Ninja Build
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake.exe --build ./build --config Release
 
  Ubuntu:
    runs-on: ubuntu-latest
    env:
      CC: clang-16
      CXX: clang++-16

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    - name: Update Apt Package List
      run: sudo apt-get update

    - name: Purge Clang
      run: sudo apt remove -y clang-13 clang-14

    - name: Setup And Install LLVM 16
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    - name: Generate Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake -DCMAKE_BUILD_TYPE=Release -S. -B./build -G Ninja

    - name: Ninja Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: cmake --build ./build --config Release
